//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactWindow) DeepCopyInto(out *ContactWindow) {
	*out = *in
	if in.TypicalInterval != nil {
		in, out := &in.TypicalInterval, &out.TypicalInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TypicalDuration != nil {
		in, out := &in.TypicalDuration, &out.TypicalDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NextExpected != nil {
		in, out := &in.NextExpected, &out.NextExpected
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactWindow.
func (in *ContactWindow) DeepCopy() *ContactWindow {
	if in == nil {
		return nil
	}
	out := new(ContactWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialExpiry) DeepCopyInto(out *CredentialExpiry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialExpiry.
func (in *CredentialExpiry) DeepCopy() *CredentialExpiry {
	if in == nil {
		return nil
	}
	out := new(CredentialExpiry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialExpiry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialExpiryList) DeepCopyInto(out *CredentialExpiryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialExpiry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialExpiryList.
func (in *CredentialExpiryList) DeepCopy() *CredentialExpiryList {
	if in == nil {
		return nil
	}
	out := new(CredentialExpiryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialExpiryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialExpirySpec) DeepCopyInto(out *CredentialExpirySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WarnBefore != nil {
		in, out := &in.WarnBefore, &out.WarnBefore
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RequiredContactWindow != nil {
		in, out := &in.RequiredContactWindow, &out.RequiredContactWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialExpirySpec.
func (in *CredentialExpirySpec) DeepCopy() *CredentialExpirySpec {
	if in == nil {
		return nil
	}
	out := new(CredentialExpirySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialExpiryStatus) DeepCopyInto(out *CredentialExpiryStatus) {
	*out = *in
	if in.NextExpiry != nil {
		in, out := &in.NextExpiry, &out.NextExpiry
		*out = (*in).DeepCopy()
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]CredentialStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialExpiryStatus.
func (in *CredentialExpiryStatus) DeepCopy() *CredentialExpiryStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialExpiryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialStatus) DeepCopyInto(out *CredentialStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.RotatableVia != nil {
		in, out := &in.RotatableVia, &out.RotatableVia
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialStatus.
func (in *CredentialStatus) DeepCopy() *CredentialStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceCapability) DeepCopyInto(out *DeviceCapability) {
	*out = *in
	if in.Transports != nil {
		in, out := &in.Transports, &out.Transports
		*out = make([]Transport, len(*in))
		copy(*out, *in)
	}
	if in.ReachableVia != nil {
		in, out := &in.ReachableVia, &out.ReachableVia
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceCapability.
func (in *DeviceCapability) DeepCopy() *DeviceCapability {
	if in == nil {
		return nil
	}
	out := new(DeviceCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLiveness) DeepCopyInto(out *DeviceLiveness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLiveness.
func (in *DeviceLiveness) DeepCopy() *DeviceLiveness {
	if in == nil {
		return nil
	}
	out := new(DeviceLiveness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceLiveness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLivenessList) DeepCopyInto(out *DeviceLivenessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceLiveness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLivenessList.
func (in *DeviceLivenessList) DeepCopy() *DeviceLivenessList {
	if in == nil {
		return nil
	}
	out := new(DeviceLivenessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceLivenessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLivenessSpec) DeepCopyInto(out *DeviceLivenessSpec) {
	*out = *in
	out.ExpectedInterval = in.ExpectedInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLivenessSpec.
func (in *DeviceLivenessSpec) DeepCopy() *DeviceLivenessSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceLivenessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLivenessStatus) DeepCopyInto(out *DeviceLivenessStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.NextExpectedBy != nil {
		in, out := &in.NextExpectedBy, &out.NextExpectedBy
		*out = (*in).DeepCopy()
	}
	if in.Capability != nil {
		in, out := &in.Capability, &out.Capability
		*out = new(DeviceCapability)
		(*in).DeepCopyInto(*out)
	}
	if in.ContactWindows != nil {
		in, out := &in.ContactWindows, &out.ContactWindows
		*out = make([]ContactWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLivenessStatus.
func (in *DeviceLivenessStatus) DeepCopy() *DeviceLivenessStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceLivenessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOutcome) DeepCopyInto(out *DeviceOutcome) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOutcome.
func (in *DeviceOutcome) DeepCopy() *DeviceOutcome {
	if in == nil {
		return nil
	}
	out := new(DeviceOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftExpectation) DeepCopyInto(out *DriftExpectation) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftExpectation.
func (in *DriftExpectation) DeepCopy() *DriftExpectation {
	if in == nil {
		return nil
	}
	out := new(DriftExpectation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftedDevice) DeepCopyInto(out *DriftedDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftedDevice.
func (in *DriftedDevice) DeepCopy() *DriftedDevice {
	if in == nil {
		return nil
	}
	out := new(DriftedDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareRollout) DeepCopyInto(out *FirmwareRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareRollout.
func (in *FirmwareRollout) DeepCopy() *FirmwareRollout {
	if in == nil {
		return nil
	}
	out := new(FirmwareRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareRolloutList) DeepCopyInto(out *FirmwareRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirmwareRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareRolloutList.
func (in *FirmwareRolloutList) DeepCopy() *FirmwareRolloutList {
	if in == nil {
		return nil
	}
	out := new(FirmwareRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareRolloutSpec) DeepCopyInto(out *FirmwareRolloutSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Source = in.Source
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = new(RolloutRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.Strategy.DeepCopyInto(&out.Strategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareRolloutSpec.
func (in *FirmwareRolloutSpec) DeepCopy() *FirmwareRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareRolloutStatus) DeepCopyInto(out *FirmwareRolloutStatus) {
	*out = *in
	if in.Refused != nil {
		in, out := &in.Refused, &out.Refused
		*out = make([]DeviceOutcome, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]DeviceOutcome, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]DeviceOutcome, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.NextWindow != nil {
		in, out := &in.NextWindow, &out.NextWindow
		*out = (*in).DeepCopy()
	}
	if in.WindowOpenedAt != nil {
		in, out := &in.WindowOpenedAt, &out.WindowOpenedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareRolloutStatus.
func (in *FirmwareRolloutStatus) DeepCopy() *FirmwareRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(FirmwareRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareSource) DeepCopyInto(out *FirmwareSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareSource.
func (in *FirmwareSource) DeepCopy() *FirmwareSource {
	if in == nil {
		return nil
	}
	out := new(FirmwareSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetDrift) DeepCopyInto(out *FleetDrift) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetDrift.
func (in *FleetDrift) DeepCopy() *FleetDrift {
	if in == nil {
		return nil
	}
	out := new(FleetDrift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetDrift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetDriftList) DeepCopyInto(out *FleetDriftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetDrift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetDriftList.
func (in *FleetDriftList) DeepCopy() *FleetDriftList {
	if in == nil {
		return nil
	}
	out := new(FleetDriftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetDriftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetDriftSpec) DeepCopyInto(out *FleetDriftSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Expect != nil {
		in, out := &in.Expect, &out.Expect
		*out = new(DriftExpectation)
		(*in).DeepCopyInto(*out)
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetDriftSpec.
func (in *FleetDriftSpec) DeepCopy() *FleetDriftSpec {
	if in == nil {
		return nil
	}
	out := new(FleetDriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetDriftStatus) DeepCopyInto(out *FleetDriftStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DriftedDevice, len(*in))
		copy(*out, *in)
	}
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetDriftStatus.
func (in *FleetDriftStatus) DeepCopy() *FleetDriftStatus {
	if in == nil {
		return nil
	}
	out := new(FleetDriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetQuery) DeepCopyInto(out *FleetQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetQuery.
func (in *FleetQuery) DeepCopy() *FleetQuery {
	if in == nil {
		return nil
	}
	out := new(FleetQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetQueryList) DeepCopyInto(out *FleetQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetQueryList.
func (in *FleetQueryList) DeepCopy() *FleetQueryList {
	if in == nil {
		return nil
	}
	out := new(FleetQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetQuerySpec) DeepCopyInto(out *FleetQuerySpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Where != nil {
		in, out := &in.Where, &out.Where
		*out = new(QueryPredicate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetQuerySpec.
func (in *FleetQuerySpec) DeepCopy() *FleetQuerySpec {
	if in == nil {
		return nil
	}
	out := new(FleetQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetQueryStatus) DeepCopyInto(out *FleetQueryStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]QueryResult, len(*in))
		copy(*out, *in)
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetQueryStatus.
func (in *FleetQueryStatus) DeepCopy() *FleetQueryStatus {
	if in == nil {
		return nil
	}
	out := new(FleetQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthGate) DeepCopyInto(out *HealthGate) {
	*out = *in
	if in.MustReportWithin != nil {
		in, out := &in.MustReportWithin, &out.MustReportWithin
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SettleFor != nil {
		in, out := &in.SettleFor, &out.SettleFor
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthGate.
func (in *HealthGate) DeepCopy() *HealthGate {
	if in == nil {
		return nil
	}
	out := new(HealthGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowList) DeepCopyInto(out *MaintenanceWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowList.
func (in *MaintenanceWindowList) DeepCopy() *MaintenanceWindowList {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowSpec) DeepCopyInto(out *MaintenanceWindowSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]WindowPeriod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]WindowPeriod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowInFlightToComplete != nil {
		in, out := &in.AllowInFlightToComplete, &out.AllowInFlightToComplete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowSpec.
func (in *MaintenanceWindowSpec) DeepCopy() *MaintenanceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowStatus) DeepCopyInto(out *MaintenanceWindowStatus) {
	*out = *in
	if in.NextOpen != nil {
		in, out := &in.NextOpen, &out.NextOpen
		*out = (*in).DeepCopy()
	}
	if in.NextClose != nil {
		in, out := &in.NextClose, &out.NextClose
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowStatus.
func (in *MaintenanceWindowStatus) DeepCopy() *MaintenanceWindowStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryPredicate) DeepCopyInto(out *QueryPredicate) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(StringMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(StringMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.ReachableVia != nil {
		in, out := &in.ReachableVia, &out.ReachableVia
		*out = new(StringMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.RunningConfigHash != nil {
		in, out := &in.RunningConfigHash, &out.RunningConfigHash
		*out = new(StringMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.OTACapable != nil {
		in, out := &in.OTACapable, &out.OTACapable
		*out = new(bool)
		**out = **in
	}
	if in.OTAReachable != nil {
		in, out := &in.OTAReachable, &out.OTAReachable
		*out = new(bool)
		**out = **in
	}
	if in.SilentLongerThan != nil {
		in, out := &in.SilentLongerThan, &out.SilentLongerThan
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SilentBeyondExpected != nil {
		in, out := &in.SilentBeyondExpected, &out.SilentBeyondExpected
		*out = new(bool)
		**out = **in
	}
	if in.BatteryBelowPercent != nil {
		in, out := &in.BatteryBelowPercent, &out.BatteryBelowPercent
		*out = new(int32)
		**out = **in
	}
	if in.Not != nil {
		in, out := &in.Not, &out.Not
		*out = new(QueryPredicate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryPredicate.
func (in *QueryPredicate) DeepCopy() *QueryPredicate {
	if in == nil {
		return nil
	}
	out := new(QueryPredicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResult) DeepCopyInto(out *QueryResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResult.
func (in *QueryResult) DeepCopy() *QueryResult {
	if in == nil {
		return nil
	}
	out := new(QueryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackTriggers) DeepCopyInto(out *RollbackTriggers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackTriggers.
func (in *RollbackTriggers) DeepCopy() *RollbackTriggers {
	if in == nil {
		return nil
	}
	out := new(RollbackTriggers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutRequirements) DeepCopyInto(out *RolloutRequirements) {
	*out = *in
	if in.MaxSilentFor != nil {
		in, out := &in.MaxSilentFor, &out.MaxSilentFor
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutRequirements.
func (in *RolloutRequirements) DeepCopy() *RolloutRequirements {
	if in == nil {
		return nil
	}
	out := new(RolloutRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.HealthGate != nil {
		in, out := &in.HealthGate, &out.HealthGate
		*out = new(HealthGate)
		(*in).DeepCopyInto(*out)
	}
	if in.RollbackOn != nil {
		in, out := &in.RollbackOn, &out.RollbackOn
		*out = new(RollbackTriggers)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
	if in.In != nil {
		in, out := &in.In, &out.In
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotIn != nil {
		in, out := &in.NotIn, &out.NotIn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WindowPeriod) DeepCopyInto(out *WindowPeriod) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = (*in).DeepCopy()
	}
	if in.Until != nil {
		in, out := &in.Until, &out.Until
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WindowPeriod.
func (in *WindowPeriod) DeepCopy() *WindowPeriod {
	if in == nil {
		return nil
	}
	out := new(WindowPeriod)
	in.DeepCopyInto(out)
	return out
}
